version: '3.8'

services:
  auth-server:
    build:
      context: ./auth-server
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=H<Ms8.cs>w,q9QX*Zn4JVm
      - AUTH_SERVICE_PORT=5000
      - DATABASE_PATH=/app/database/auth.db
    volumes:
      - auth-data:/app/database

  restapi:  
    build:
      context: ./restapi
    ports:
      - "3000:3000"
    environment:
      - REST_API_PORT=3000
      - DATABASE_PATH=/app/database/rest.db
      - AUTH_SERVICE_URL=http://auth-server:5000
    volumes:
      - rest-data:/app/database
    depends_on:
      - auth-server  

  graphqlapi:
    build:
      context: ./graphqlapi
    ports:
      - "4000:4000"
    environment:
      - GRAPHQL_API_PORT=4000
      - AUTH_SERVICE_URL=http://auth-server:5000
      - REST_API_BASE_URL=http://restapi:3000 
    depends_on:
      - auth-server
      - restapi  

volumes:
  auth-data:
  rest-data:
